### ISSUE TITLE
Error when using commands

### ISSUE THREAD

**Issue by abhi147h** [Apipa169/Assistant-Relay-for-Hassio#19]
Hello
I am unable to send any rest_command, nothing happens
In logs i get this error message
Error. Url: http://192.168.0.44:3000/assistant. Status code 500.

The URL works correctly it opens the webui of Assistant relay

I have added the rest_command my IP and user in it in configuration.yaml

**Comment by Apipa169** [comment]
Can you post the configuration?

**Comment by abhi147h** [comment]
You mean what i put in config.yaml?
Then thats this.

rest_command:
  assistant_broadcast:
    url: http://192.168.0.44:3000/assistant
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "user":"abhishek", "broadcast":true}'
    
  assistant_converse:
    url: http://192.168.0.44:3000/assistant
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "user":"abhishek", "converse":true}'

  assistant_relay:
    url: http://192.168.0.44:3000/assistant
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "user":"abhishek"}'

**Comment by Apipa169** [comment]
Yes, that is what I mean. Your config looks fine.

What do you see in the log of the addon when you send a command?

**Comment by jazzyisj** [comment]
I get the same error in my HA log.

```
WARNING (MainThread) [homeassistant.components.rest_command] Error. Url: http://192.168.1.110:3000/assistant. Status code 500
```
Doesn't work in sandbox either.  For example a broadcast command gives me this error.

```
14 UNAVAILABLE: Getting metadata from plugin failed with error: Cannot read property 'access_token' of undefined
```

My config.
```
rest_command:
  assistant_broadcast:
    url: http://192.168.1.110:3000/assistant
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "user":"Jason", "broadcast":true}'
    
  assistant_converse:
    url: http://192.168.1.110:3000/assistant
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "user":"Jason", "converse":true}'

  assistant_relay:
    url: http://192.168.1.110:3000/assistant
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "user":"Jason"}'  
```
Assistant Relay log

```
0|www  | POST /server/updateConfig 200 98.064 ms - 16
0|www  | Assistant Relay Server Initialized
0|www  | Visit http://172.30.33.0:3000 in a browser to configure
0|www  | An update is available. Please visit https://github.com/greghesp/assistant-relay/releases
0|www  | POST /server/updateConfig 200 43.430 ms - 16
0|www  | POST /server/getResponses 200 40.518 ms - 16
0|www  | POST /server/getConfig 200 44.069 ms - 125
0|www  | GET /server/users 304 53.162 ms - -
0|www  | POST /server/getConfig 200 32.825 ms - 125
0|www  | GET /server/users 304 44.552 ms - -
0|www  | POST /server/getConfig 200 33.366 ms - 125
0|www  | Auth error:TypeError: Cannot read property 'access_token' of undefined
0|www  | Error: 14 UNAVAILABLE: Getting metadata from plugin failed with error: Cannot read property 'access_token' of undefined
0|www  |     at Object.exports.createStatusError (/assistant_relay/node_modules/grpc/src/common.js:91:15)
0|www  |     at ClientDuplexStream._emitStatusIfDone (/assistant_relay/node_modules/grpc/src/client.js:233:26)
0|www  |     at ClientDuplexStream._receiveStatus (/assistant_relay/node_modules/grpc/src/client.js:211:8)
0|www  |     at Object.onReceiveStatus (/assistant_relay/node_modules/grpc/src/client_interceptors.js:1311:15)
0|www  |     at InterceptingListener._callNext (/assistant_relay/node_modules/grpc/src/client_interceptors.js:568:42)
0|www  |     at InterceptingListener.onReceiveStatus (/assistant_relay/node_modules/grpc/src/client_interceptors.js:618:8)
0|www  |     at /assistant_relay/node_modules/grpc/src/client_interceptors.js:1127:18 {
0|www  |   code: 14,
0|www  |   metadata: Metadata { _internal_repr: {}, flags: 0 },
0|www  |   details: "Getting metadata from plugin failed with error: Cannot read property 'access_token' of undefined"
0|www  | }
0|www  | POST /assistant 500 341.693 ms - 140
```
