### ISSUE TITLE
converse: google is just repeating my command

### ISSUE THREAD

**Issue by pergolafabio** [Apipa169/Assistant-Relay-for-Hassio#27]
ok, i have this setup as addon
if i use this service: rest_command.assistant_converse
with command: tell me a joke

then my google devices are waking up, i hear then
broadcasting from xxx , tell me a joke

in other words, the google devices are just repeating my command? i was expecting that google would tell me a joke?

```
  assistant_converse:
    url: http://192.168.0.17:3000/assistant
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "user":"Fabio", "converse":true}'
```
