### ISSUE TITLE
Unable to cast

### ISSUE THREAD

**Issue by tungmeister** [Apipa169/Assistant-Relay-for-Hassio#46]
I'm attempting to cast via the catt component using the beta version. Based on the instructions shown here https://greghesp.github.io/assistant-relay/docs/cast/casting I've setup the following rest_command:

```
  bedroom_cast:
    url: http://10.0.0.11:3000/cast
    method: POST
    content_type: 'application/json'
    payload: '{"device":"10.0.0.148", "source":"http://10.0.0.11:8123/local/tileboard/index.html", "type":"website"}'
```

but in the log I'm seeing:

```
Error. Url: http://10.0.0.11:3000/cast. Status code 404. Payload: b'{"device":"10.0.0.148", "source":"http://10.0.0.11:8123/local/tileboard/index.html", "type":"website"}'
Home Assistant has started!

```
should this be working with the beta?
