### ISSUE TITLE
Assistant Relay beta 4.0 Not working outside sandbox

### ISSUE THREAD

**Issue by LeoCalbi** [Apipa169/Assistant-Relay-for-Hassio#47]
**Describe the bug**
Beta version of Assistant Relay 4.0.0.b works fine inside sandbox, but /assistant page result in a 404 Not Found error from everywhere else

**To Reproduce**
1. Go to 'Home Assistant'
2. Click on 'Test Broadcast'
```yaml
# Example test lovelace card
type: entities
entities:
  - action_name: Broadcast
    name: test broadcast
    service: rest_command.assistant_broadcast
    type: call-service
    service_data:
      command: hello, this is a test broadcast
```
3. Scroll down to 'Settings - Logs'

```yaml
Logger: homeassistant.components.rest_command
Source: components/rest_command/__init__.py:131
Integration: RESTful Command (documentation, issues)
First occurred: 15:28:11 (4 occurrences)
Last logged: 15:32:57

Error. Url: http://192.168.0.51:3000/assistant. Status code 404. Payload: b'{"command":"hello, this is a test broadcast", "user":"Assistant Relay", "broadcast":true}'
```
The sandbox works fine.

The same 404 error is present even with a raw curl call to the page:

```bash
curl -X POST http://192.168.0.51:3000/assistant -H "Content-Type: application/json" -d '{"command":"Prova", "user":"Assistant Relay", "broadcast":true}'
```

**Expected behavior**
Broadcast message to Google devices

**System (please complete the following information):**
Hassio version: Supervisor 245 channel Stable
System: HassOS 4.13
