### ISSUE TITLE
AR BETA fixes & readme

### ISSUE THREAD

**Issue by ComputaBloke** [Apipa169/Assistant-Relay-for-Hassio#77]
**Is your feature request related to a problem? Please describe.**

I found some teething issues getting started with Assistant Relay BETA. Beta seems much better for security, more advanced Sandbox, and tracking History of calls/responses, so would be great to get the experience a little smoother.
I managed to get it up and working through a process of troubleshooting, reviewing logs, Github issues for the greghesp repos, and web-debugging the built-in 'Sandbox' application to examine the REST api calls required to interact with it.

So, sharing some further information which might help others.
Summary:
a) ```config.json``` and ```audio-responses``` directory needs to be created on host, and volume bindings set in docker to container directory: ```/assistant-relay/bin/```.
b) URL path changed to: ```/api/assistant```
c) Passing the API key as an ```Authorization``` header.
d) ```converse``` seems to be now ```talkback```
e) Beta 4.02b seems to be a bit out of date when 4.04b is available

**Describe the solution you'd like**

Update the Beta ```README.md``` with further information.
Suggested edits for BETA:

*The IP must be the IP address of your system, not the one mentioned in the log as this is the address of the container. The port is 3000 by default, however you have to create this ```config.json``` file and a writable ```audio-responses``` directory before the container will start.*

##### Providing or changing the port number and directory for audio-responses
The Assistant Relay beta requires 'host' network.
Assistant Relay Web UI will start on default port 3000 if you provide a ```/usr/share/hassio/assistant_relay/config.json``` file containing:
```json
{
    "port":3000
}
```
Also create a directory: ```/usr/share/hassio/assistant_relay/audio-responses```

Re-configure the container to provide required volume bindings before starting.
Example:
```
docker run -d --name addon_6a3d001f_assistant_relay_beta \
--network host \
-v /usr/share/hassio/assistant_relay/config.json:/assistant-relay/bin/config.json:rw \
-v /usr/share/hassio/assistant_relay/audio-responses:/assistant-relay/bin/audio-responses:rw \
apipa169/assistant-relay:beta
```
Then the Add-on docker container should start.
Launch through browser on the configured port. E.g. http://192.168.1.2:3000
Go through initial setup to configure a user account.
Through the 'Access Control' page of AR, generate an Access/API Key.
Update homeassistant's ```secrets.yaml``` with the API Key in order for [REST command](https://www.home-assistant.io/integrations/rest_command/)s to work. (see: https://www.home-assistant.io/docs/configuration/secrets/)

## Examples
User needs always to be the user you used in the setup of AR. Multiple users are supported by AR.
The API key has been added to ```secrets.yaml```.

#### Home Assistant REST
Example command to broadcast via a rest command.
```yaml
# Example configuration.yaml
rest_command:
  assistant_broadcast:
    url: http://192.168.10.2:3000/api/assistant
    method: POST
    content_type: 'application/json'
    headers:
        authorization: !secret assistant_relay_apikey
    payload: '{"command":"{{ command }}", "user":"username", "broadcast":true, "device":"Home hub"}'
    
  assistant_converse:
    url: http://192.168.10.2:3000/api/assistant
    method: POST
    content_type: 'application/json'
    headers:
        authorization: !secret assistant_relay_apikey
    payload: '{"command":"{{ command }}", "user":"username", "talkback":true, "device":"Home hub"}'

  assistant_relay:
    url: http://192.168.10.2:3000/api/assistant
    method: POST
    content_type: 'application/json'
    headers:
        authorization: !secret assistant_relay_apikey
    payload: '{"command":"{{ command }}", "user":"username", "device":"Home hub"}'
```

```yaml
# Automation action example (just fill in "command: hello" if you are using the editor)
  action:
  - data:
      command: hello
    service: rest_command.assistant_broadcast
```
