### ISSUE TITLE
Doesn't broadcast

### ISSUE THREAD

**Issue by krzysiek2788** [Apipa169/Assistant-Relay-for-Hassio#84]
**Describe the bug**
When I try to broadcast to my google home mini I is quiet, Assistant Relay is getting messages on the list but Google home mini stays quiet. When I first setup user, it broadcast message but that's all.

**System (please complete the following information):**
Hassio version: Home Assistant OS 5.13
System: 2021.4.6

**Additional context**
My Assistant Relay is on IP: 192.168.0.16 and Google Home mini is on 192.168.0.11 and below is my configuration did I missed something? I tried in Sandbox and from Home assistant Dev tools but always the same result, message show in Assistant Relay only.
```
rest_command:
  assistant_broadcast:
    url: http://192.168.0.16:3000/assistant
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "user":"Kuchnia", "broadcast":true}'
    
  assistant_converse:
    url: http://192.168.0.16:3000/assistant
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "user":"Kuchnia", "converse":true}'

  assistant_relay:
    url: http://192.168.0.16:3000/assistant
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "user":"Kuchnia"}'
```
