### ISSUE TITLE
Cannot destructure property `user`

### ISSUE THREAD

**Issue by schwarzenbergf** [Apipa169/Assistant-Relay-for-Hassio#9]
AR is working for me now, the problem with the blank Google pop-up has been solved with the updated add-on.
After starting the add-on and configuring the Auth-Code stuff the add-on gives a success message over my Google Home devices. Using the AR WEB page (Sandbox) everything is working fine.
But trying to use the add-on in HA (Hassio) does not succeed. I get the following error message in the Log:

> 0|www  | Assistant Relay Server Initialized
0|www  | Visit http://172.30.33.8:3000 in a browser to configure
0|www  | GET / 304 3.760 ms - -
0|www  | GET /static/css/2.25de4381.chunk.css 304 1.095 ms - -
0|www  | GET /static/js/2.e91f5ff5.chunk.js 304 1.232 ms - -
0|www  | GET /static/js/main.9d79ef78.chunk.js 304 0.446 ms - -
0|www  | POST /server/userCount 200 14.711 ms - 10
0|www  | POST /server/getResponses 200 7.976 ms - 326
0|www  | POST /server/addUser 200 11.135 ms - 297
0|www  | POST /server/processOAuth 200 304.725 ms - -
0|www  | POST /server/getResponses 200 8.909 ms - 326
0|www  | POST /server/getConfig 200 7.887 ms - 126
0|www  | Conversation Complete
0|www  | POST /assistant 200 1276.261 ms - 93
0|www  | TypeError: Cannot destructure property `user` of 'undefined' or 'null'.
0|www  |     at /assistant_relay/routes/index.js:25:11
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  | POST /assistant 500 53.180 ms - 60
0|www  | TypeError: Cannot destructure property `user` of 'undefined' or 'null'.
0|www  |     at /assistant_relay/routes/index.js:25:11
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  | POST /assistant 500 23.484 ms - 60
0|www  | TypeError: Cannot destructure property `user` of 'undefined' or 'null'.
0|www  |     at /assistant_relay/routes/index.js:25:11
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  | POST /assistant 500 18.769 ms - 60
0|www  | POST /server/getConfig 200 6.768 ms - 126
0|www  | POST /server/getResponses 200 7.189 ms - 401
0|www  | POST /server/getConfig 200 10.339 ms - 126

>
 I added another user using the WEB page but same result.

In  configuration.yaml I have the following setup:
```yaml
rest_command:
  assistant_broadcast:
    url: http://192.168.2.118:3000/assistant
    method: POST
    content_type: 'application/json'
    payload: '{"user":"Frank", "command":"{{ command }}", "broadcast":true, "converse":false}'
    
  assistant_converse:
    url: http://192.168.2.118:3000/assistant
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "user":"Frank", "converse":true}'

  assistant_relay:
    url: http://192.168.2.118:3000/assistant
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "user":"Frank"}'
```
Trying this from Node-RED or with curl
(curl -d '{"command":"hello world",  "user": "Frank", "broadcast":true}' -H "Content-Type: application/json" -X POST http://192.168.2.118:3000/assistant)
gives the same result:
> Cannot destructure property `user`

> 
(error 500).

The automation command looks like this:
```yaml
  - service: rest_command.assistant_broadcast
    data:
       command: Stromausfall
```
Any ideas what I'm doing wrong?
